name: ci
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      # Prepare

      - name: Checkout
        uses: actions/checkout@v4

      # Build and push image

      - if: github.ref == 'refs/heads/main'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: github.ref == 'refs/heads/main'
        name: Build and push image
        run: make push